name: proofpack-metrics
on:
  push:
  schedule:
    - cron: "30 18 * * *"   # 12:00 AM IST
jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: python -m pip install -U pip
      - run: python 07_data_behavior/make_metrics.py
      - run: python 07_data_behavior/make_badges.py
      - name: Commit metrics
        run: |
          git config user.name "proofpack-bot"
          git config user.email "bot@users.noreply.github.com"
          git add public/metrics.json
          git commit -m "chore: refresh telemetry" || echo "no changes"
          git push
